# Generated by Django 3.2.8 on 2021-11-03 11:53

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('img', models.CharField(blank=True, max_length=200, null=True, verbose_name='Img link')),
                ('status', models.CharField(max_length=40, verbose_name='Status')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='City')),
                ('county', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
