# Generated by Django 3.2.8 on 2021-10-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last name')),
                ('img', models.CharField(blank=True, max_length=200, null=True, verbose_name='Img link')),
                ('status', models.CharField(max_length=40, verbose_name='Status')),
                ('follow', models.BooleanField(default=False, verbose_name='Follow')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='City')),
                ('county', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country')),
            ],
        ),
    ]
